// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA47I-VNYTDbSzLUnDheAzTlHhQmf4RzRw',
    appId: '1:974997062576:web:be402864329470cb570c75',
    messagingSenderId: '974997062576',
    projectId: 'music-book-d43fd',
    authDomain: 'music-book-d43fd.firebaseapp.com',
    storageBucket: 'music-book-d43fd.appspot.com',
    measurementId: 'G-QPMVWKDVYW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAqUfIKjtFekrkOiryhVpDwfr7ZHnOs6CI',
    appId: '1:974997062576:android:a9b91818d3c1e120570c75',
    messagingSenderId: '974997062576',
    projectId: 'music-book-d43fd',
    storageBucket: 'music-book-d43fd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBYWIAMrO5fjhirX7ChMbvROMxwle4Of9c',
    appId: '1:974997062576:ios:282ce7914c96e7eb570c75',
    messagingSenderId: '974997062576',
    projectId: 'music-book-d43fd',
    storageBucket: 'music-book-d43fd.appspot.com',
    iosClientId: '974997062576-igc45cpl61v8b596858tcaj9b13a2h0v.apps.googleusercontent.com',
    iosBundleId: 'com.example.musicbook',
  );
}
